// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_lang from "./routes/api/lang.ts";
import * as $index from "./routes/index.tsx";
import * as $KittyCanvas from "./islands/KittyCanvas.tsx";
import * as $Nav from "./islands/Nav.tsx";
import * as $PwaUpdate from "./islands/PwaUpdate.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/lang.ts": $api_lang,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/KittyCanvas.tsx": $KittyCanvas,
    "./islands/Nav.tsx": $Nav,
    "./islands/PwaUpdate.tsx": $PwaUpdate,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
